CWorkshop = CWorkshop or {}

-- DO NOT USE LINKED COLLECTIONS!!!

-- GARRY'S MOD CANNOT TELL THE DIFFERENCE BETWEEN A COLLECTION
-- AND AN ADDON WITH REQUIREMENTS! CAN CAUSE AN INFINITE LOOP
CWorkshop.Collection = 3307830375